name: Android Fastlane with Firebase App Distribution

on:
  push:
    branches:
      - master
jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code!
      uses: actions/checkout@v2
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
       channel: stable
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.1'
        working-directory: android

    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: | 
        bundle exec fastlane android firebase_distribution
      working-directory: android