name: Android Fastlane with Firebase App Distribution

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code!
      uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3' # Use a stable Ruby version
        working-directory: android

    - name: Add Linux platform to Bundler
      run: |
        cd android
        bundle lock --add-platform x86_64-linux

    - name: Install Fastlane and Dependencies
      run: |
        cd android
        bundle install --force


    - name: Install Fastlane Plugins
      run: |
        cd android
        bundle exec fastlane install_plugins

    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        cd android
        bundle exec fastlane android firebase_distribution

    # Fallback step if bundle install fails
    - name: Remove Gemfile.lock and Retry (if needed)
      if: failure()
      run: |
        cd android
        rm -f Gemfile.lock
        bundle install