name: Android Fastlane with Firebase App Distribution

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code!
      uses: actions/checkout@v4

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
       channel: stable

    - name: Get Flutter Dependencies
      run: flutter pub get
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.1'
        bundler-cache: true
        working-directory: android

    - name: Install Fastlane Plugins
      run: bundle exec fastlane install_plugins
      working-directory: android

    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        cd android
        bundle exec fastlane android firebase_distribution
